repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        language: python
        additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-print]
  - repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
      - id: isort
        language: python
        exclude: __init__.py
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: no-commit-to-branch
        args: [--branch=master]
      - id: pretty-format-json
        args: [--indent=2, --autofix, --no-sort-keys]
