dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .[tensorflow,tests]
  - pip install -r docs/requirements.txt
script:
  # format, lint, mypy
  - black . --check
  - flake8
  - find . -name "*.py" | xargs mypy
  # tests
  - python -m pytest --cov=barrage --cov-config=setup.cfg tests/
  # doc tests
  - cd docs
  - make html
  - cd ..
after_success:
  - coveralls
