dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .[tests]
  - pip install -r docs/requirements.txt
script:
  # format, lint, imports, mypy
  - black . --check
  - flake8
  - isort --check
  - find . -name "*.py" | xargs mypy
  # tests
  - pytest -vv --cov=barrage --cov-config=setup.cfg tests/
  # doc tests
  - cd docs && make html && cd ..
after_success:
  - codecov
