dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .[tensorflow,tests]
  - pip install -r docs/requirements.txt
script:
  - flake8
  - black . --check
  - find . -name "*.py" | xargs mypy
  - pytest -vv
  - cd docs && make html
after_success:
  - coverall
